name: Android CI

on: [push]

jobs:
  build-debug:

    runs-on: ubuntu-latest

    steps:
    - name: Repo Visualizer
      uses: githubocto/repo-visualizer@0.8.2
    - uses: actions/checkout@v1
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: build app apk
      run: ./gradlew :app:assembleChargeDebug;
    - name: build imitate apk
      run: ./gradlew :imitate:assembleDebug;

  build-release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 11
        uses: actions/setup-java@v2
        with:
         java-version: '11'
         distribution: 'adopt'
      - name: build app apk
        run: ./gradlew :app:assembleChargeRelease;
      - name: build imitate apk
        run: ./gradlew :imitate:assembleRelease;
